#pragma once

#include "primeon/math/scalar/scalar.hpp"
#include "primeon/math/vector/vector3.hpp"
#include "primeon/geometry/primitives/aabb.hpp"
#include <algorithm>
#include <vector>

namespace primeon::collision {

using math::f32;
using math::u32;

// ── Sweep and Prune (SAP) Broadphase ────────────────────────────────────────
//
// Maintains sorted endpoint lists along each axis. Pairs are generated by
// sweeping X and checking Y/Z overlap using sorted endpoint lookups.

struct SAPEndpoint {
    f32 value = 0.0f;
    u32 bodyId = 0;
    bool isMax = false;

    [[nodiscard]] constexpr bool operator<(const SAPEndpoint& rhs) const noexcept {
        if (value != rhs.value) return value < rhs.value;
        if (isMax != rhs.isMax) return isMax;
        return bodyId < rhs.bodyId;
    }
};

struct SAPPair {
    u32 bodyA = 0;
    u32 bodyB = 0;
};

struct SAPBroadphase {
    std::vector<SAPEndpoint> endpoints[3] = {};
    std::vector<SAPPair> pairs = {};
    u32 bodyCount = 0;

    void insert(u32 bodyId, const math::AABB& aabb) noexcept {
        bodyCount++;
        endpoints[0].push_back({aabb.min.x, bodyId, false});
        endpoints[0].push_back({aabb.max.x, bodyId, true});
        endpoints[1].push_back({aabb.min.y, bodyId, false});
        endpoints[1].push_back({aabb.max.y, bodyId, true});
        endpoints[2].push_back({aabb.min.z, bodyId, false});
        endpoints[2].push_back({aabb.max.z, bodyId, true});
        for (int i = 0; i < 3; ++i)
            std::sort(endpoints[i].begin(), endpoints[i].end());
    }

    void remove(u32 bodyId) noexcept {
        for (int i = 0; i < 3; ++i) {
            endpoints[i].erase(
                std::remove_if(endpoints[i].begin(), endpoints[i].end(),
                    [bodyId](const SAPEndpoint& e) { return e.bodyId == bodyId; }),
                endpoints[i].end());
        }
        if (bodyCount > 0) bodyCount--;
    }

    void update(u32 bodyId, const math::AABB& aabb) noexcept {
        remove(bodyId);
        insert(bodyId, aabb);
    }

    void clear() noexcept {
        for (int i = 0; i < 3; ++i) endpoints[i].clear();
        pairs.clear();
        bodyCount = 0;
    }

    void computePairs() noexcept {
        pairs.clear();
        if (bodyCount < 2) return;

        // Sweep X axis. For each body that becomes X-active, check all
        // currently X-active bodies for Y and Z overlap.
        std::vector<u32> xActive;
        xActive.reserve(bodyCount);

        // Helper: check if two bodyIds overlap on a given axis.
        auto overlapsOnAxis = [&](int axis, u32 idA, u32 idB) -> bool {
            f32 minA = 0, maxA = 0, minB = 0, maxB = 0;
            bool foundA[2] = {false, false};
            bool foundB[2] = {false, false};
            for (const auto& e : endpoints[axis]) {
                if (e.bodyId == idA) {
                    if (!e.isMax && !foundA[0]) { minA = e.value; foundA[0] = true; }
                    if (e.isMax && !foundA[1]) { maxA = e.value; foundA[1] = true; }
                }
                if (e.bodyId == idB) {
                    if (!e.isMax && !foundB[0]) { minB = e.value; foundB[0] = true; }
                    if (e.isMax && !foundB[1]) { maxB = e.value; foundB[1] = true; }
                }
                if (foundA[0] && foundA[1] && foundB[0] && foundB[1]) break;
            }
            return !(maxA <= minB || maxB <= minA);
        };

        for (const auto& e : endpoints[0]) {
            if (!e.isMax) {
                // Body becomes X-active. Check all currently X-active bodies.
                for (u32 other : xActive) {
                    if (overlapsOnAxis(1, e.bodyId, other) &&
                        overlapsOnAxis(2, e.bodyId, other)) {
                        pairs.push_back({e.bodyId, other});
                    }
                }
                xActive.push_back(e.bodyId);
            } else {
                auto it = std::find(xActive.begin(), xActive.end(), e.bodyId);
                if (it != xActive.end()) xActive.erase(it);
            }
        }
    }

    [[nodiscard]] constexpr u32 pairCount() const noexcept {
        return static_cast<u32>(pairs.size());
    }

    [[nodiscard]] constexpr u32 numBodies() const noexcept {
        return bodyCount;
    }
};

} // namespace primeon::collision
